openapi: 3.0.0

components:
  requestBodies:
    # APTITUDE
    PostSampleNonGenericBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              test:
                type: string
            required:
              - test
